### ISSUE TITLE
[CONCEPTION] Option to enable scrolling and disable pagination

### ISSUE THREAD

**Issue by LePhenix47** [LePhenix47/HRnet-Data-Table_npm-package#8]
# Option to enable scrolling and disable pagination:
![image](https://user-images.githubusercontent.com/78600723/217193593-e77dc2bd-2bf4-42a9-9e1d-1b7666431142.png)

# Composition:
Just like a normal table, although we need to add these CSS properties to the `<table>` element:
```css
.table{
    display: block;
    max-height: 500px; /* For example */
    overflow-y: scroll;
}
```

# Features
**The user can pass in a boolean value...:**
- `true` if they want to have pagination with the index tables
-  `false` if they want to have scrolling on the table

**Comment by LePhenix47** [comment]
Demo: 

https://user-images.githubusercontent.com/78600723/217268657-52f7c941-2820-4699-a7bf-c2415302b894.mp4

**Comment by LePhenix47** [comment]
It needs to have a set height in order to work

So when the scrolling is enabled with a set height, it needs to:
- Hide the `<ShownEntries />` component
- Hide the `<PaginationIndex />` component
- Display `Showing [TotalData] entries` and  `Showing [TotalDataFiltered] entries (filtered from [TotalData])` if filtered
- Change the SASS of the `<table>` like this:
```scss
.DataTable {
    &__body--scroll{
        display: block;
        max-height: 500px;
        overflow-y: scroll;
    }
}
```
